require:
  - rubocop-rspec
inherit_mode:
  merge:
    - Exclude
AllCops:
  NewCops: enable
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
RSpec/FilePath:
  Enabled: false
Style/Documentation:
  Enabled: false
#-------------------------------------------------------------------------------
RSpec/ExampleLength:
  Exclude:
    - spec/integration/repository_spec.rb
    - spec/unit/repository_spec.rb
    - spec/unit/structs/attributter_spec.rb
    - spec/unit/structs/beliggenhedsadresse_spec.rb
    - spec/unit/structs/beskaeftigelse_spec.rb
    - spec/unit/structs/branche_spec.rb
    - spec/unit/structs/deltagerperson_spec.rb
    - spec/unit/structs/kommune_spec.rb
    - spec/unit/structs/livsforloeb_spec.rb
    - spec/unit/structs/navne_spec.rb
    - spec/unit/structs/penheder_spec.rb
    - spec/unit/structs/postadresse_spec.rb
    - spec/unit/structs/reg_nummer_spec.rb
    - spec/unit/structs/tele_nummer_spec.rb
    - spec/unit/structs/vaerdier_spec.rb
    - spec/unit/structs/virksomhedsstatus_spec.rb
RSpec/MessageSpies:
  Exclude:
    - spec/unit/repository_spec.rb
    - spec/unit/services/es_index_creator_spec.rb
RSpec/MultipleExpectations:
  Exclude:
    - spec/integration/repository_spec.rb
    - spec/unit/repository_spec.rb
    - spec/unit/structs/attributter_spec.rb
    - spec/unit/structs/beliggenhedsadresse_spec.rb
    - spec/unit/structs/beskaeftigelse_spec.rb
    - spec/unit/structs/branche_spec.rb
    - spec/unit/structs/deltagerperson_spec.rb
    - spec/unit/structs/kommune_spec.rb
    - spec/unit/structs/livsforloeb_spec.rb
    - spec/unit/structs/navne_spec.rb
    - spec/unit/structs/penheder_spec.rb
    - spec/unit/structs/periode_spec.rb
    - spec/unit/structs/postadresse_spec.rb
    - spec/unit/structs/reg_nummer_spec.rb
    - spec/unit/structs/tele_nummer_spec.rb
    - spec/unit/structs/vaerdier_spec.rb
    - spec/unit/structs/virksomhedsstatus_spec.rb
RSpec/NamedSubject:
  Exclude:
    - spec/integration/repository_spec.rb
    - spec/unit/repository_spec.rb
    - spec/unit/services/es_index_creator_spec.rb
RSpec/StubbedMock:
  Exclude:
    - spec/unit/repository_spec.rb
RSpec/VerifiedDoubles:
  Exclude:
    - spec/unit/repository_spec.rb
    - spec/unit/services/es_index_creator_spec.rb
